# Generated by Django 5.2.4 on 2025-07-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('aviso-legal', 'Aviso Legal'), ('privacidad', 'Política de Privacidad'), ('cookies', 'Política de Cookies'), ('terminos', 'Términos y Condiciones')], unique=True, verbose_name='Identificador')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido (HTML permitido)')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible en la web')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': 'Página legal/informativa',
                'verbose_name_plural': 'Páginas legales/informativas',
                'ordering': ['slug'],
            },
        ),
    ]
