# Generated by Django 5.2.4 on 2025-07-19 16:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_pagina_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='contenido',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido (HTML permitido)'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
