# Generated by Django 5.2.4 on 2025-07-20 16:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('contenido', ckeditor.fields.RichTextField(verbose_name='Contenido (HTML permitido)')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Mostrar desde')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Mostrar hasta')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['orden', '-fecha_modificacion'],
            },
        ),
    ]
