# Generated by Django 5.2.4 on 2025-07-13 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('icono', models.ImageField(blank=True, null=True, upload_to='alergenos/', verbose_name='Icono')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Alérgeno',
                'verbose_name_plural': 'Alérgenos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de Visualización')),
                ('activa', models.BooleanField(default=True, verbose_name='Categoría Activa')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio')),
                ('tipo_plato', models.CharField(choices=[('ENTRANTE', 'Entrante'), ('PRINCIPAL', 'Plato Principal'), ('POSTRE', 'Postre'), ('BEBIDA', 'Bebida'), ('ESPECIAL', 'Especial del Día')], default='PRINCIPAL', max_length=20, verbose_name='Tipo de Plato')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='platos/', verbose_name='Imagen')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('tiempo_preparacion', models.PositiveIntegerField(default=15, verbose_name='Tiempo de Preparación (minutos)')),
                ('popularidad', models.PositiveIntegerField(default=0, verbose_name='Contador de Popularidad')),
                ('ingredientes', models.TextField(blank=True, null=True, verbose_name='Ingredientes')),
                ('calorias', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calorías')),
                ('es_vegetariano', models.BooleanField(default=False, verbose_name='Es Vegetariano')),
                ('es_vegano', models.BooleanField(default=False, verbose_name='Es Vegano')),
                ('es_sin_gluten', models.BooleanField(default=False, verbose_name='Sin Gluten')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden en la Carta')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('alergenos', models.ManyToManyField(blank=True, to='carta.alergeno', verbose_name='Alérgenos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carta.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Plato',
                'verbose_name_plural': 'Platos',
                'ordering': ['categoria__orden', 'orden', 'nombre'],
            },
        ),
    ]
