# Generated by Django 5.2.4 on 2025-07-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.CharField(verbose_name='Enlace o email'),
        ),
    ]
