# Generated by Django 5.2.4 on 2025-07-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionHorarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Configuración')),
                ('intervalo_reservas', models.PositiveIntegerField(default=30, verbose_name='Intervalo de Reservas (minutos)')),
                ('anticipacion_minima', models.PositiveIntegerField(default=60, verbose_name='Anticipación Mínima (minutos)')),
                ('anticipacion_maxima', models.PositiveIntegerField(default=30, verbose_name='Anticipación Máxima (días)')),
                ('duracion_reserva', models.PositiveIntegerField(default=120, verbose_name='Duración de Reserva (minutos)')),
                ('activa', models.BooleanField(default=True, verbose_name='Configuración Activa')),
            ],
            options={
                'verbose_name': 'Configuración de Horarios',
                'verbose_name_plural': 'Configuraciones de Horarios',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la Semana')),
                ('hora_apertura', models.TimeField(verbose_name='Hora de Apertura')),
                ('hora_cierre', models.TimeField(verbose_name='Hora de Cierre')),
                ('cerrado', models.BooleanField(default=False, verbose_name='Cerrado')),
                ('activo', models.BooleanField(default=True, verbose_name='Horario Activo')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['dia_semana'],
                'unique_together': {('dia_semana',)},
            },
        ),
        migrations.CreateModel(
            name='HorarioEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('FESTIVO', 'Festivo'), ('VACACIONES', 'Vacaciones'), ('EVENTO', 'Evento Especial'), ('MANTENIMIENTO', 'Mantenimiento')], max_length=20, verbose_name='Tipo')),
                ('hora_apertura', models.TimeField(blank=True, null=True, verbose_name='Hora de Apertura')),
                ('hora_cierre', models.TimeField(blank=True, null=True, verbose_name='Hora de Cierre')),
                ('cerrado', models.BooleanField(default=False, verbose_name='Cerrado')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Horario Especial',
                'verbose_name_plural': 'Horarios Especiales',
                'ordering': ['-fecha'],
                'unique_together': {('fecha',)},
            },
        ),
    ]
